### ISSUE TITLE
Post-development checklist

### ISSUE THREAD

**Issue by AustinGreen** [llamaxyz/llama#167]
This is a list of potential small features that we should explore post-development but pre-audit:

- [x]  Refundable approvals/disapprovals: automatically refund gas used for approvals and disapprovals
- [x]  Set ENS reverse records on core, policy, account and strategy initialization. This would allow users to request payments to an ENS name vs an ETH address
- [x]  Ensure consistency with open zeppelin governor when possible (eg. castApproval vs submitApproval). It will make it easier for other clients to integrate 
- [x] Add the correct policy SVG design #53
- [ ] #57
- [ ] #59
- [x] #140
- [x] #143
- [ ] Should we capture date created to display on the policy svg? similar to this: https://worldcoin.org/blog/announcements/introducing-world-id-and-sdk
- [ ] #65
- [ ] https://github.com/llama-community/vertex-v1/issues/117
- [ ]  https://github.com/llama-community/vertex-v1/issues/165
- [x] https://github.com/llama-community/vertex-v1/issues/55
- [x] After refactoring the policy contract, we may able be able to pre-compute the strategy address from the entire strategy struct (instead of part of it).
- [x] Multichain EVM deployment #44
