### ISSUE TITLE
Audit Checklist

### ISSUE THREAD

**Issue by 0xrajath** [llamaxyz/llama#82]
We need to do our own internal audit run to check that all best practices are covered:

- [x] Set `FOUNDRY_PROFILE: ci` under `env` in `ci.yml`.
- [x] https://github.com/llama-community/vertex-v1/issues/151
- [ ] ~~Add gas report generation to `ci.yml`~~
- [ ] Ensure all contracts and interfaces have appropriate natspec (functions, variables, etc.)
- [x] https://github.com/llama-community/vertex-v1/issues/152
- [ ] ~~Get vertex verfied on https://sourcify.dev/~~
- [x] Re-Add `--sizes` flag to `build` process in `ci.yml` (https://github.com/llama-community/vertex-v1/issues/157)
- [x] https://github.com/llama-community/vertex-v1/issues/163
- [ ] ~~https://github.com/llama-community/vertex-v1/issues/162~~
- [x] https://github.com/llama-community/vertex-v1/issues/160
- [ ] ~~https://github.com/llama-community/vertex-v1/issues/154~~
- [ ] ~~https://github.com/llama-community/vertex-v1/issues/135~~
- [x] https://github.com/llama-community/vertex-v1/issues/124
- [x] Scan through all remaining `TODO` in the codebase and see if they need to be sorted out.
- [ ] ~~Decide between explicit return statements or implicit returns. Currently we use both throughout the codebase.~~
- [x] https://github.com/llama-community/vertex-v1/issues/205
- [ ] Take a pass through all public/external methods in all contracts to ensure inputs are validated
- [x] Check if we have `onlyVertex` modifier or other modifiers in all appropriate external and public functions throughout the codebase.
- [ ] De-dupe custom errors throughout the codebase and ensure they're all logical, consistent and not vague.
- [x] Use absolute imports through out the codebase (I.e `import {XYZ} from "src/XYZ.sol"`) and cleanup leftover imports.
- [x] https://github.com/transmissions11/solcurity#events states not to evaluate expressions in within event arguments as order of evaluation is unpredicatable. We do have some instances of this in the codebase. Clean it up.
- [x] Use `policyholder` instead of `user` throughout codebase.
- [x] Use `<=` or `>` for all timestamp comparison.
- [x] Review all individual vertex instance dependencies on the factory contract (authorized implementations, token uri, etc.)
- [x] Check if we need to restructure the repo in /src, /test, /script etc after all the changes to make the architecture more obvious.
- [ ] Rearrange all getters to below the state changing functions in the contracts in the codebase.
- [x] Check if any remaining addresses need to be strongly typed throughout the codebase (i.e VertexCore in Policy, Account, etc.)
- [x] Delegate call in createAction in VertexCore
- [ ] #52
- [ ] #83
- [ ] Gas optimizations: #193
- [ ] Organizes structs: https://github.com/llama-community/vertex/pull/239#discussion_r1168040929. And move all structs to the respective contract instead of `Structs.sol`
- [x] Check if all variables and function names throughout the codebase follow camel case.
- [x] When roles are repurposed - we need to emit an event. 
- [ ] Check `encodePacked` usage and see if we should replace with `encodeWithSelector` or `bytes.concat` (e.g. `executeAction` is one spot we probably should do this)
- [x] Run slither
- [x] Check if `vm.expectEmit()` is used before every emit in tests (Especially when there's a block of emits).
- [x] Decide if we want to prevent race condition of new role IDs changing before your role+strategy is created
- [x] Consider adding e.g. `uint256[99] private __gap;` like openzeppelin does to reduce chance of a delegatecalled script writing to vertex core storage, and consider checking that slot 0 (initializable data) does not change after ca ll
- [x] Consider renaming `minExecutionTime` to `endOfQueuingPeriod` or `dissapprovalPeriodEnd` or some variation of this. Review the Approval, Queuing and Execution phases.
